### ISSUE TITLE
ORM Compatibility Checklist

### ISSUE THREAD

**Issue by assertchris** [assertchris/silvershift#1]
- [ ] `DataObject::get()` → `DataList`
- [ ] `DataObject::byID($id)` → `DataObject`
- [ ] `DataObject::first()` → `DataObject`
- [ ] `DataObject::last()` → `DataObject`
- [ ] `DataObject::sort(string $column, string $direction)` → `DataList`
- [ ] `DataObject::sort([string $column => string $direction])` → `DataList`
- [ ] `DataObject::filter(string $column, mixed $value)` → `DataList`
- [ ] `DataObject::filter([string $column => mixed $value])` → `DataList`
- [ ] `DataObject::filterAny(string $column, mixed $value)` → `DataList`
- [ ] `DataObject::filterAny([string $column => mixed $value])` → `DataList`
- [ ] `DataObject::filterByCallback($callback(DataObject $item, DataList $list))` → `DataList`
- [ ] `DataObject::exclude(string $column, mixed $value)` → `DataList`
- [ ] `DataObject::exclude([string $column => mixed $value])` → `DataList`
- [ ] `DataObject::limit(int $limit, int $offset)` → `DataList`
- [ ] `DataObject->write()` → `bool`
- [ ] `DataObject->delete()` → `bool`

- [ ] `DataList->first()` → `DataObject`
- [ ] `DataList->last()` → `DataObject`
- [ ] `DataList->all()` → `ArrayList`
- [ ] `DataList->sort(string $column, string $direction)` → `DataList`
- [ ] `DataList->sort([string $column => string $direction])` → `DataList`
- [ ] `DataList->filter(string $column, mixed $value)` → `DataList`
- [ ] `DataList->filter([string $column => mixed $value])` → `DataList`
- [ ] `DataList->filterAny(string $column, mixed $value)` → `DataList`
- [ ] `DataList->filterAny([string $column => mixed $value])` → `DataList`
- [ ] `DataList->filterByCallback($callback(DataObject $item, DataList $list))` → `DataList`
- [ ] `DataList->exclude(string $column, mixed $value)` → `DataList`
- [ ] `DataList->exclude([string $column => mixed $value])` → `DataList`
- [ ] `DataList->where(string $clause)` → `DataList`
- [ ] `DataList->where([string $clause])` → `DataList`
- [ ] `DataList->whereAny(string $clause)` → `DataList`
- [ ] `DataList->whereAny([string $clause])` → `DataList`
- [ ] `DataList->limit(int $limit, int $offset)` → `DataList`
- [ ] `DataList->subtract(DataList $dataList)` → `DataList`
- [ ] `DataList->count()` → `int`
- [ ] `DataList->max()` → `float`
- [ ] `DataList->min()` → `float`
- [ ] `DataList->avg()` → `float`
- [ ] `DataList->sum()` → `float`
- [ ] `DataList->column(string $column)` → `ArrayList`
- [ ] `DataList->byID(int $id)` → `DataObject`
- [ ] `DataList->byIDs([int $id])` → `ArrayList`
